from app.services.entity_resolution import CompanyEntityResolver


# Starter catalog covering the initial liquid NSE universe plus selected
# multinational companies listed in India. Expand this catalog incrementally.
NSE_ENTITY_CATALOG: dict[str, dict[str, object]] = {
    "RELIANCE": {"name": "Reliance Industries", "aliases": ["Reliance", "RIL"]},
    "TCS": {"name": "Tata Consultancy Services", "aliases": ["TCS", "Tata Consultancy"]},
    "INFY": {"name": "Infosys", "aliases": ["Infosys Limited", "Infosys Ltd"]},
    "HDFCBANK": {"name": "HDFC Bank", "aliases": ["HDFC Bank Limited", "HDFC"]},
    "ICICIBANK": {"name": "ICICI Bank", "aliases": ["ICICI Bank Limited", "ICICI"]},
    "SBIN": {"name": "State Bank of India", "aliases": ["SBI", "State Bank"]},
    "BHARTIARTL": {"name": "Bharti Airtel", "aliases": ["Airtel", "Bharti Airtel Limited"]},
    "ITC": {"name": "ITC", "aliases": ["ITC Limited"]},
    "LT": {"name": "Larsen & Toubro", "aliases": ["Larsen and Toubro", "L&T", "Larsen & Toubro Limited"]},
    "AXISBANK": {"name": "Axis Bank", "aliases": ["Axis Bank Limited", "Axis"]},
    "KOTAKBANK": {"name": "Kotak Mahindra Bank", "aliases": ["Kotak Bank", "Kotak Mahindra"]},
    "HINDUNILVR": {"name": "Hindustan Unilever", "aliases": ["HUL", "Hindustan Unilever Limited"]},
    "MARUTI": {"name": "Maruti Suzuki India", "aliases": ["Maruti Suzuki", "Maruti"]},
    "SUNPHARMA": {"name": "Sun Pharmaceutical Industries", "aliases": ["Sun Pharma", "Sun Pharmaceutical"]},
    "TATAMOTORS": {"name": "Tata Motors", "aliases": ["Tata Motors Limited"]},
    "M&M": {"name": "Mahindra & Mahindra", "aliases": ["Mahindra and Mahindra", "Mahindra"]},
    "WIPRO": {"name": "Wipro", "aliases": ["Wipro Limited"]},
    "HCLTECH": {"name": "HCL Technologies", "aliases": ["HCL Tech", "HCL Technologies Limited"]},
    "ADANIENT": {"name": "Adani Enterprises", "aliases": ["Adani Enterprises Limited"]},
    "NTPC": {"name": "NTPC", "aliases": ["NTPC Limited"]},
    "POWERGRID": {"name": "Power Grid Corporation of India", "aliases": ["Power Grid", "POWERGRID"]},
    "COALINDIA": {"name": "Coal India", "aliases": ["Coal India Limited"]},
    "ULTRACEMCO": {"name": "UltraTech Cement", "aliases": ["UltraTech", "Ultratech Cement"]},
    "TITAN": {"name": "Titan Company", "aliases": ["Titan Company Limited", "Titan"]},
    "ASIANPAINT": {"name": "Asian Paints", "aliases": ["Asian Paints Limited"]},
    "NESTLEIND": {"name": "Nestle India", "aliases": ["Nestlé India", "Nestle"]},
    "TECHM": {"name": "Tech Mahindra", "aliases": ["Tech Mahindra Limited"]},
    "CIPLA": {"name": "Cipla", "aliases": ["Cipla Limited"]},
    "DRREDDY": {"name": "Dr. Reddy's Laboratories", "aliases": ["Dr Reddy's", "Dr Reddy", "Dr. Reddy"]},
    "BAJFINANCE": {"name": "Bajaj Finance", "aliases": ["Bajaj Finance Limited"]},
    "BAJAJFINSV": {"name": "Bajaj Finserv", "aliases": ["Bajaj Finserv Limited"]},
    "ADANIPORTS": {"name": "Adani Ports and Special Economic Zone", "aliases": ["Adani Ports", "Adani Ports SEZ"]},
    "APOLLOHOSP": {"name": "Apollo Hospitals Enterprise", "aliases": ["Apollo Hospitals"]},
    "ONGC": {"name": "Oil and Natural Gas Corporation", "aliases": ["ONGC", "Oil and Natural Gas Corporation Limited"]},
    "BPCL": {"name": "Bharat Petroleum Corporation", "aliases": ["BPCL", "Bharat Petroleum"]},
    "TATASTEEL": {"name": "Tata Steel", "aliases": ["Tata Steel Limited"]},
    "JSWSTEEL": {"name": "JSW Steel", "aliases": ["JSW Steel Limited"]},
    "EICHERMOT": {"name": "Eicher Motors", "aliases": ["Eicher Motors Limited", "Royal Enfield"]},
    "HEROMOTOCO": {"name": "Hero MotoCorp", "aliases": ["Hero Motocorp", "Hero MotoCorp Limited"]},
    "BRITANNIA": {"name": "Britannia Industries", "aliases": ["Britannia Industries Limited"]},
    "GRASIM": {"name": "Grasim Industries", "aliases": ["Grasim Industries Limited"]},
    "HINDALCO": {"name": "Hindalco Industries", "aliases": ["Hindalco", "Hindalco Industries Limited"]},
    "DIVISLAB": {"name": "Divi's Laboratories", "aliases": ["Divis Laboratories", "Divi's Lab", "Divis Lab"]},
    "INDUSINDBK": {"name": "IndusInd Bank", "aliases": ["IndusInd Bank Limited"]},
    "TRENT": {"name": "Trent", "aliases": ["Trent Limited"]},
    "ETERNAL": {"name": "Eternal", "aliases": ["Zomato", "Zomato Limited"]},
    "BEL": {"name": "Bharat Electronics", "aliases": ["BEL", "Bharat Electronics Limited"]},
    "HAL": {"name": "Hindustan Aeronautics", "aliases": ["HAL", "Hindustan Aeronautics Limited"]},
    # Selected multinational companies listed on NSE/BSE.
    "HINDPETRO": {"name": "Hindustan Petroleum", "aliases": ["HPCL", "Hindustan Petroleum Corporation"]},
    "ABB": {"name": "ABB India", "aliases": ["ABB"]},
    "SIEMENS": {"name": "Siemens", "aliases": ["Siemens India"]},
    "BOSCHLTD": {"name": "Bosch", "aliases": ["Bosch India"]},
    "COLPAL": {"name": "Colgate-Palmolive India", "aliases": ["Colgate Palmolive", "Colgate"]},
    "PGHH": {"name": "Procter & Gamble Hygiene and Health Care", "aliases": ["P&G", "Procter & Gamble"]},
}

resolver = CompanyEntityResolver(NSE_ENTITY_CATALOG)
